'use client'

import { useMemo, useState, type ReactNode } from 'react'
import { ArrowUpRight, BadgeCheck, Bell, Bot, ChevronDown, ChevronRight, CircleDot, Clock3, CreditCard, Ellipsis, LayoutDashboard, Menu, MoreHorizontal, Package, Plus, Search, Settings, Sparkles, TrendingUp, Truck, Users, X, type LucideIcon } from 'lucide-react'

const menu: [string, LucideIcon][] = [['Overview', LayoutDashboard], ['Orders', Package], ['Customers', Users], ['Pickups & delivery', Clock3], ['Payments', CreditCard]]
const secondary: [string, LucideIcon][] = [['Analytics', TrendingUp], ['AI assistant', Bot], ['Settings', Settings]]
type Order = { id: string; customer: string; items: string; status: string; time: string; tone: string }
const initialOrders: Order[] = [
  { id: '#LD-2849', customer: 'Amina Wanjiku', items: '3 items', status: 'Ready', time: 'Today, 4:30 PM', tone: 'emerald' },
  { id: '#LD-2848', customer: 'David Kamau', items: '7 items', status: 'Washing', time: 'Today, 6:00 PM', tone: 'blue' },
  { id: '#LD-2847', customer: 'Maya Chen', items: '2 items', status: 'Quality check', time: 'Tomorrow, 10:00 AM', tone: 'violet' },
  { id: '#LD-2846', customer: 'Joel Otieno', items: '5 items', status: 'Ironing', time: 'Tomorrow, 12:30 PM', tone: 'amber' },
]

function IconButton({ children, label }: { children: ReactNode; label: string }) { return <button className="icon-button" aria-label={label}>{children}</button> }

export default function Dashboard() {
  const [sidebar, setSidebar] = useState(false)
  const [active, setActive] = useState('Overview')
  const [searchOpen, setSearchOpen] = useState(false)
  const [newOrderOpen, setNewOrderOpen] = useState(false)
  const [toast, setToast] = useState('')
  const [orders, setOrders] = useState<Order[]>(initialOrders)
  const today = useMemo(() => new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date()), [])
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2700) }
  const navigate = (name: string) => { setActive(name); setSidebar(false) }
  const createOrder = (customer: string, quantity: string) => {
    setOrders(current => [{ id: `#LD-${2850 + current.length}`, customer, items: `${quantity} items`, status: 'Received', time: 'Just now', tone: 'blue' }, ...current])
    setNewOrderOpen(false); navigate('Orders'); notify(`Order created for ${customer}`)
  }
  return <main className="app-shell">
    <aside className={`sidebar ${sidebar ? 'mobile-open' : ''}`}>
      <div className="brand"><div className="brand-mark"><CircleDot size={20}/><i><Sparkles size={10}/></i></div><span>Laundry<span>OS</span></span><button className="close-mobile" onClick={() => setSidebar(false)} aria-label="Close menu"><X size={19}/></button></div>
      <div className="workspace"><div className="workspace-icon">L</div><div><strong>Lavender Laundry</strong><small>Nairobi, Kenya</small></div><ChevronDown size={15}/></div>
      <nav>{menu.map(([name, Icon]) => <button onClick={() => navigate(name)} className={active === name ? 'nav-item active' : 'nav-item'} key={name}><Icon size={18}/><span>{name}</span>{name === 'Orders' && <b>{orders.length}</b>}</button>)}<div className="nav-label">WORKSPACE</div>{secondary.map(([name, Icon]) => <button onClick={() => navigate(name)} className={active === name ? 'nav-item active' : 'nav-item'} key={name}><Icon size={18}/><span>{name}</span>{name === 'AI assistant' && <em>new</em>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="upgrade"><div className="upgrade-icon"><Sparkles size={14}/></div><div><strong>Unlock more with AI</strong><small>7 days left on your trial</small></div><ChevronRight size={16}/></div><div className="user"><div className="avatar">AK</div><div><strong>Amina K.</strong><small>Owner</small></div><MoreHorizontal size={18}/></div></div>
    </aside>
    <section className="content">
      <header className="topbar"><button className="hamburger" onClick={() => setSidebar(true)} aria-label="Open menu"><Menu size={21}/></button><div className="crumb"><span>Workspace</span><ChevronRight size={14}/><strong>{active}</strong></div><div className="top-actions"><button className="search" onClick={() => setSearchOpen(true)}><Search size={17}/><span>Search anything...</span><kbd>Ctrl K</kbd></button><IconButton label="Notifications"><Bell size={19}/><i className="notification-dot"/></IconButton><button className="add-button" onClick={() => setNewOrderOpen(true)}><Plus size={17}/> New order</button></div></header>
      <div className="dashboard">{active === 'Overview' ? <Overview today={today} orders={orders} notify={notify} navigate={navigate}/> : <WorkspaceView active={active} orders={orders} navigate={navigate} notify={notify}/>}</div>
    </section>
    {searchOpen && <div className="modal-backdrop" onClick={() => setSearchOpen(false)}><div className="command-modal" onClick={e => e.stopPropagation()}><div><Search size={19}/><input autoFocus placeholder="Search orders, customers, or actions..."/><kbd>ESC</kbd></div><p>QUICK ACTIONS</p><button onClick={() => { setSearchOpen(false); setNewOrderOpen(true) }}><span><Plus size={15}/></span>Create a new order<ChevronRight size={16}/></button><button onClick={() => { setSearchOpen(false); navigate('AI assistant') }}><span><Sparkles size={15}/></span>Open AI assistant<ChevronRight size={16}/></button><button onClick={() => { setSearchOpen(false); navigate('Pickups & delivery') }}><span><Truck size={15}/></span>View today’s pickups<ChevronRight size={16}/></button></div></div>}
    {newOrderOpen && <NewOrder onClose={() => setNewOrderOpen(false)} onCreate={createOrder}/>} {toast && <div className="toast"><Sparkles size={16}/>{toast}</div>}
  </main>
}

function Overview({ today, orders, notify, navigate }: { today: string; orders: Order[]; notify: (m: string) => void; navigate: (n: string) => void }) { return <><section className="welcome"><div><p className="eyebrow">{today}</p><h1>Good morning, Amina <Sparkles size={18}/></h1><p className="muted">Here’s what’s happening with your business today.</p></div><button className="ai-pulse" onClick={() => navigate('AI assistant')}><span><Sparkles size={17}/></span><div><strong>Ask LaundryOS AI</strong><small>Get your daily business briefing</small></div><ChevronRight size={17}/></button></section><section className="metrics"><Metric label="TODAY'S REVENUE" value="KSh 48,250" trend="12.5%" icon={<ArrowUpRight size={16}/>} tone="blue"/><Metric label="ORDERS IN PROGRESS" value="32" trend="8 more than yesterday" icon={<CircleDot size={16}/>} tone="purple"/><Metric label="PENDING PICKUPS" value="8" trend="3 scheduled this afternoon" icon={<Truck size={16}/>} tone="amber"/><Metric label="BUSINESS HEALTH" value="92" trend="Excellent performance" icon={<Sparkles size={16}/>} tone="emerald" health/></section><section className="grid-top"><Revenue/><div className="panel ai-insight"><div className="panel-head"><div><p className="section-label">AI INSIGHT</p><h2>Keep your momentum</h2></div><button className="dots"><Ellipsis size={18}/></button></div><div className="insight-orb"><Sparkles size={21}/></div><p>Your weekday revenue is <strong>23% higher</strong> than last month. Tuesday and Thursday are your strongest days.</p><button className="link-button" onClick={() => navigate('AI assistant')}>View full analysis <ChevronRight size={15}/></button></div></section><section className="grid-bottom"><OrdersPanel orders={orders.slice(0, 4)} onViewAll={() => navigate('Orders')}/><ServicePanel notify={notify}/></section></> }

function Revenue() { return <div className="panel revenue"><div className="panel-head"><div><p className="section-label">REVENUE OVERVIEW</p><h2>KSh 384,920 <span className="positive"><ArrowUpRight size={11}/>18.2%</span></h2><p className="muted">vs. KSh 325,790 last month</p></div><button className="period">This month <ChevronDown size={14}/></button></div><div className="chart"><div className="y-axis"><span>50k</span><span>35k</span><span>20k</span><span>0</span></div><svg viewBox="0 0 720 210" preserveAspectRatio="none" aria-label="Revenue chart"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#4f7cff" stopOpacity=".3"/><stop offset="1" stopColor="#4f7cff" stopOpacity="0"/></linearGradient></defs><path className="grid-lines" d="M0 20H720M0 78H720M0 136H720M0 194H720"/><path d="M0 168 C35 151 45 160 72 140 S110 120 133 132 S170 146 196 109 S230 84 253 104 S290 140 318 124 S350 82 380 96 S414 116 441 78 S480 40 510 68 S544 94 570 72 S602 38 628 56 S671 83 720 22 V210 H0Z" fill="url(#area)"/><path className="chart-line" d="M0 168 C35 151 45 160 72 140 S110 120 133 132 S170 146 196 109 S230 84 253 104 S290 140 318 124 S350 82 380 96 S414 116 441 78 S480 40 510 68 S544 94 570 72 S602 38 628 56 S671 83 720 22"/></svg><div className="months"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span></div></div></div> }

function OrdersPanel({ orders, onViewAll }: { orders: Order[]; onViewAll: () => void }) { return <div className="panel orders-panel"><div className="panel-head"><div><p className="section-label">OPERATIONS</p><h2>Recent orders</h2></div><button className="text-button" onClick={onViewAll}>View all <ChevronRight size={15}/></button></div><div className="order-list">{orders.map(o => <OrderRow order={o} key={o.id}/>)}</div></div> }
function OrderRow({ order }: { order: Order }) { return <div className="order-row"><div className="order-avatar">{order.customer.split(' ').map(s => s[0]).join('')}</div><div className="order-name"><strong>{order.customer}</strong><small>{order.id} · {order.items}</small></div><span className={`status ${order.tone}`}><i/> {order.status}</span><div className="order-time">{order.time}</div><button className="row-more" aria-label={`More options for ${order.id}`}><MoreHorizontal size={18}/></button></div> }
function ServicePanel({ notify }: { notify: (m: string) => void }) { const services = [['Wash & Fold', '42%', 72, '#4f7cff'], ['Dry Cleaning', '31%', 54, '#8b5cf6'], ['Express Service', '18%', 32, '#f59e0b']] as const; return <div className="panel service"><div className="panel-head"><div><p className="section-label">SERVICE PERFORMANCE</p><h2>Top services</h2></div><button className="dots"><Ellipsis size={18}/></button></div>{services.map(s => <div className="service-row" key={s[0]}><div className="service-title"><span style={{ background: s[3] }}/><strong>{s[0]}</strong><b>{s[1]}</b></div><div className="progress"><i style={{ width: `${s[2]}%`, background: s[3] }}/></div></div>)}<button className="report" onClick={() => notify('Your service report is ready')}>View service report <ChevronRight size={15}/></button></div> }
function WorkspaceView({ active, orders, navigate, notify }: { active: string; orders: Order[]; navigate: (n: string) => void; notify: (m: string) => void }) { if (active === 'Orders') return <><section className="page-title"><div><p className="eyebrow">OPERATIONS</p><h1>Orders</h1><p className="muted">Track every garment from pickup to delivery.</p></div><button className="add-button" onClick={() => notify('Use the New order button to create an order')}><Plus size={17}/> New order</button></section><OrdersPanel orders={orders} onViewAll={() => {}}/></>; const config: Record<string, [string, string, LucideIcon]> = { Customers: ['Customers', 'Your customer directory is ready for your next import.', Users], 'Pickups & delivery': ['Pickups & delivery', 'You have 8 pickups scheduled today.', Truck], Payments: ['Payments', 'Today’s payments are on track.', CreditCard], Analytics: ['Analytics', 'Explore how your business is performing.', TrendingUp], 'AI assistant': ['LaundryOS AI', 'Ask a question about your orders, customers, or performance.', Bot], Settings: ['Settings', 'Manage your workspace preferences.', Settings] }; const [title, description, Icon] = config[active]; return <section className="empty-state panel"><div className="empty-icon"><Icon size={25}/></div><p className="section-label">{active === 'AI assistant' ? 'YOUR BUSINESS COPILOT' : 'WORKSPACE'}</p><h1>{title}</h1><p className="muted">{description}</p><button className="add-button" onClick={() => notify(active === 'AI assistant' ? 'AI briefing is being prepared' : `${title} module is coming next`)}>{active === 'AI assistant' ? <><Sparkles size={16}/> Get daily briefing</> : <>Explore {title}</>}</button></section> }
function NewOrder({ onClose, onCreate }: { onClose: () => void; onCreate: (customer: string, quantity: string) => void }) { const [customer, setCustomer] = useState(''); const [quantity, setQuantity] = useState(''); return <div className="modal-backdrop" onClick={onClose}><form className="new-order-modal" onClick={e => e.stopPropagation()} onSubmit={e => { e.preventDefault(); if (customer.trim() && quantity.trim()) onCreate(customer.trim(), quantity.trim()) }}><div className="modal-title"><div><p className="section-label">NEW ORDER</p><h2>Create an order</h2></div><button type="button" className="close-form" onClick={onClose} aria-label="Close"><X size={18}/></button></div><label>Customer name<input autoFocus value={customer} onChange={e => setCustomer(e.target.value)} placeholder="e.g. Janet Mwangi" required/></label><label>Number of items<input value={quantity} onChange={e => setQuantity(e.target.value.replace(/[^0-9]/g, ''))} inputMode="numeric" placeholder="e.g. 4" required/></label><label>Service<select defaultValue="Wash & Fold"><option>Wash & Fold</option><option>Dry Cleaning</option><option>Express Service</option></select></label><div className="form-actions"><button type="button" className="cancel-button" onClick={onClose}>Cancel</button><button className="add-button" type="submit"><Package size={16}/> Create order</button></div></form></div> }
function Metric({ label, value, trend, icon, tone, health }: { label: string; value: string; trend: string; icon: ReactNode; tone: string; health?: boolean }) { return <div className="metric-card"><div className={`metric-icon ${tone}`}>{icon}</div><p>{label}</p><div className="metric-value">{value}{health && <span className="health-ring">%</span>}</div><small className={tone === 'amber' ? '' : 'up'}>{tone === 'amber' ? <CircleDot size={10}/> : <ArrowUpRight size={11}/>} {trend}</small></div> }
